/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


QBA LIU 2023 -------------------------------------------------------------------------------------------------------------------------------------------------------

*/


#include<stdio.h>

int main()
{

int array[33];
int n;
int i;
int sum;

array[0] = 1;
array[1] = 2;
n = 0;
sum = 0;

//populating the Fibonacci sequence ------------------------------------------------------------------------------------------------------------------------------------
while (array[n+1] < 4000000)
{
	array[n+2] = array[n] + array[n+1];
	n = n + 1;
}

// calculating the sum ----------------------------------------------------------------------------------------------------------------------------------------------
for (i = 0; i <= 33; ++i)
{
	if (array[i]%2 == 0)
	{
		sum = sum + array[i];
	}


}

printf("%d\n", sum);
return(0);
}
