"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


QBA LIU 2023 ---------------------------------------------------------------------------------------------------------------------------


"""


# populating the Fibonacci sequence --------------------------------------------------------------------------------------------------
fibonacci_sequence = [1,2]
maximum = 4000000

while fibonacci_sequence[-1] < maximum:
    new = fibonacci_sequence[-1] + fibonacci_sequence[-2]
    fibonacci_sequence.append(new)

fibonacci_sequence.pop(-1) # we have to remove the last element, because the while loop is enterted one more time



# summing the even valued terms under 4000000 ----------------------------------------------------------------------------------------
even_sum = 0

for i in fibonacci_sequence:
    if i%2 == 0:
        even_sum = even_sum + i

print(even_sum)
